# Generated by Django 6.1.1 on 2026-10-02 10:17

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DHANUser',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=255, unique=True)),
                ('password_hash', models.CharField(max_length=255)),
                ('role', models.CharField(choices=[('user', 'Normal User'), ('admin', 'Administrator')], default='user', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('disabled', 'Disabled')], default='active', max_length=20)),
                ('last_login_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'db_table': 'users',
                'ordering': ['-created_at'],
                'managed': False,
            },
        ),
        migrations.RunSQL(
            sql="""
            CREATE TABLE IF NOT EXISTS users (
                id UUID PRIMARY KEY,
                name VARCHAR(100) NOT NULL,
                email VARCHAR(255) UNIQUE NOT NULL,
                password_hash VARCHAR(255) NOT NULL,
                role VARCHAR(20) NOT NULL DEFAULT 'user',
                status VARCHAR(20) NOT NULL DEFAULT 'active',
                last_login_at TIMESTAMP WITH TIME ZONE,
                created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
                updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
            );
            """,
            reverse_sql="-- noop",
        ),
        migrations.AlterModelOptions(
            name='adminauditlog',
            options={'ordering': ['-created_at'], 'verbose_name': 'Audit Log', 'verbose_name_plural': 'Audit Logs'},
        ),
        migrations.AddField(
            model_name='adminauditlog',
            name='details',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='adminauditlog',
            name='ip_address',
            field=models.CharField(blank=True, default='', max_length=45),
        ),
        migrations.AddField(
            model_name='adminauditlog',
            name='target_model',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='adminauditlog',
            name='target_object_id',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='e.g. HDFC Salary Account, Cash Wallet', max_length=100)),
                ('account_type', models.CharField(choices=[('bank', 'Bank Account'), ('cash', 'Physical Cash'), ('credit_card', 'Credit Card'), ('investment', 'Investment / Demat'), ('wallet', 'Digital Wallet'), ('other', 'Other')], default='bank', max_length=30)),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('currency', models.CharField(default='INR', max_length=3)),
                ('institution_name', models.CharField(blank=True, help_text='e.g. HDFC, ICICI, SBI', max_length=100)),
                ('account_number_mask', models.CharField(blank=True, help_text='e.g. •••• 4321', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='core.dhanuser')),
            ],
            options={
                'verbose_name': 'Account',
                'verbose_name_plural': 'Accounts',
                'db_table': 'dhan_accounts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='e.g. Nifty 50 Index, Sovereign Gold Bond', max_length=150)),
                ('asset_type', models.CharField(choices=[('stock', 'Stocks & Mutual Funds'), ('crypto', 'Cryptocurrency'), ('real_estate', 'Real Estate'), ('gold', 'Precious Metals / Gold'), ('fixed_deposit', 'Fixed Deposit'), ('cash', 'Cash & Equivalents'), ('other', 'Other Asset')], max_length=30)),
                ('current_value', models.DecimalField(decimal_places=2, max_digits=15)),
                ('purchase_price', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='core.dhanuser')),
            ],
            options={
                'verbose_name': 'Asset',
                'verbose_name_plural': 'Assets',
                'db_table': 'dhan_assets',
                'ordering': ['-current_value'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('category_type', models.CharField(choices=[('expense', 'Expense'), ('income', 'Income'), ('transfer', 'Transfer')], default='expense', max_length=20)),
                ('icon', models.CharField(blank=True, help_text='Material or Ionic icon name', max_length=50)),
                ('color', models.CharField(blank=True, help_text='Hex color code e.g. #FF5733', max_length=20)),
                ('is_default', models.BooleanField(default=True, help_text='Default platform category')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subcategories', to='core.category')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'db_table': 'dhan_categories',
                'ordering': ['category_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('period', models.CharField(choices=[('monthly', 'Monthly'), ('weekly', 'Weekly'), ('yearly', 'Yearly')], default='monthly', max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='budgets', to='core.dhanuser')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budgets', to='core.category')),
            ],
            options={
                'verbose_name': 'Budget',
                'verbose_name_plural': 'Budgets',
                'db_table': 'dhan_budgets',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='e.g. Emergency Fund, New Bike, Vacation', max_length=150)),
                ('target_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('current_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('target_date', models.DateField()),
                ('status', models.CharField(choices=[('in_progress', 'In Progress'), ('achieved', 'Achieved'), ('paused', 'Paused'), ('cancelled', 'Cancelled')], default='in_progress', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='goals', to='core.dhanuser')),
            ],
            options={
                'verbose_name': 'Goal',
                'verbose_name_plural': 'Goals',
                'db_table': 'dhan_goals',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Liability',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='e.g. SBI Home Loan, Car Loan', max_length=150)),
                ('liability_type', models.CharField(choices=[('mortgage', 'Home Loan / Mortgage'), ('auto_loan', 'Vehicle Loan'), ('personal_loan', 'Personal Loan'), ('credit_card', 'Credit Card Outstanding'), ('student_loan', 'Education Loan'), ('other', 'Other Debt')], max_length=30)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('remaining_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('interest_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('monthly_emi', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='liabilities', to='core.dhanuser')),
            ],
            options={
                'verbose_name': 'Liability',
                'verbose_name_plural': 'Liabilities',
                'db_table': 'dhan_liabilities',
                'ordering': ['-remaining_amount'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=150)),
                ('message', models.TextField()),
                ('notification_type', models.CharField(choices=[('alert', 'Security Alert'), ('reminder', 'Bill Reminder'), ('budget', 'Budget Exceeded Warning'), ('system', 'System Update'), ('transaction', 'Transaction Confirmation')], default='system', max_length=30)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='core.dhanuser')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'db_table': 'dhan_notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RecurringPayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='e.g. Netflix Subscription, House Rent, Gym', max_length=150)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('yearly', 'Yearly')], default='monthly', max_length=20)),
                ('next_due_date', models.DateField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('cancelled', 'Cancelled')], default='active', max_length=20)),
                ('auto_pay', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.account')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.category')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='recurring_payments', to='core.dhanuser')),
            ],
            options={
                'verbose_name': 'Recurring Payment',
                'verbose_name_plural': 'Recurring Payments',
                'db_table': 'dhan_recurring_payments',
                'ordering': ['next_due_date'],
            },
        ),
        migrations.CreateModel(
            name='SplitGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('currency', models.CharField(default='INR', max_length=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(db_column='created_by_id', on_delete=django.db.models.deletion.CASCADE, related_name='created_groups', to='core.dhanuser')),
            ],
            options={
                'verbose_name': 'Group',
                'verbose_name_plural': 'Groups',
                'db_table': 'dhan_groups',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SplitExpense',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=150)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('split_type', models.CharField(choices=[('equal', 'Equal Split'), ('exact', 'Exact Amounts'), ('percentage', 'Percentage')], default='equal', max_length=20)),
                ('date', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('paid_by', models.ForeignKey(db_column='paid_by_id', on_delete=django.db.models.deletion.CASCADE, related_name='paid_splits', to='core.dhanuser')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='splits', to='core.splitgroup')),
            ],
            options={
                'verbose_name': 'Split',
                'verbose_name_plural': 'Splits',
                'db_table': 'dhan_splits',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Settlement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('status', models.CharField(choices=[('completed', 'Completed'), ('pending', 'Pending Verification'), ('cancelled', 'Cancelled')], default='completed', max_length=20)),
                ('settled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('payee', models.ForeignKey(db_column='payee_id', on_delete=django.db.models.deletion.CASCADE, related_name='settlements_received', to='core.dhanuser')),
                ('payer', models.ForeignKey(db_column='payer_id', on_delete=django.db.models.deletion.CASCADE, related_name='settlements_paid', to='core.dhanuser')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='settlements', to='core.splitgroup')),
            ],
            options={
                'verbose_name': 'Settlement',
                'verbose_name_plural': 'Settlements',
                'db_table': 'dhan_settlements',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('transaction_type', models.CharField(choices=[('expense', 'Expense'), ('income', 'Income'), ('transfer', 'Transfer')], max_length=20)),
                ('date', models.DateTimeField(help_text='Transaction execution timestamp')),
                ('note', models.TextField(blank=True, help_text='User transaction description')),
                ('status', models.CharField(choices=[('completed', 'Completed'), ('pending', 'Pending'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='completed', max_length=20)),
                ('is_recurring', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='core.account')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='core.category')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='core.dhanuser')),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
                'db_table': 'dhan_transactions',
                'ordering': ['-date'],
            },
        ),
    ]
