"""add_transaction_fields_phase5

Revision ID: ea02c7effc30
Revises: 55d64240ddfb
Create Date: 2026-10-02 17:06:12.615876

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ea02c7effc30'
down_revision: Union[str, None] = '55d64240ddfb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dhan_transactions', sa.Column('destination_account_id', sa.UUID(), nullable=True))
    op.add_column('dhan_transactions', sa.Column('description', sa.String(length=255), server_default=sa.text("''"), nullable=False))
    op.create_foreign_key('fk_dhan_transactions_destination_account_id', 'dhan_transactions', 'dhan_accounts', ['destination_account_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_dhan_transactions_destination_account_id', 'dhan_transactions', type_='foreignkey')
    op.drop_column('dhan_transactions', 'description')
    op.drop_column('dhan_transactions', 'destination_account_id')
    # ### end Alembic commands ###
